services:
  # Backend (Apache + PHP)
  - type: web
    name: backend-service
    runtime: docker
    repo: https://github.com/pabmarnav/Proyecto_Despliegue
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    rootScope: backend
    envVars:
      - key: MYSQL_HOST
        value: 34.197.49.83
      - key: MYSQL_DATABASE
        value: films
      - key: MYSQL_USER
        value: produser
      - key: MYSQL_PASSWORD
        value: prodpassword
      - key: MYSQL_ROOT_PASSWORD
        value: prodrootpassword

  # Frontend (Apache + HTML/JS)
  - type: web
    name: frontend-service
    runtime: docker
    repo: https://github.com/pabmarnav/Proyecto_Despliegue
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    rootScope: frontend
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend-service
          property: url
