services:
  # Base de datos MySQL (Ef√≠mera)
  - type: pserv
    name: mysqldb
    runtime: docker
    dockerfilePath: ./database/Dockerfile
    dockerContext: ./database
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: films
      - key: MYSQL_USER
        value: produser
      - key: MYSQL_PASSWORD
        generateValue: true

  # Backend (Apache + PHP)
  - type: web
    name: backend-service
    runtime: docker
    repo: https://github.com/pabmarnav/Proyecto_Despliegue
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    rootScope: backend
    envVars:
      - key: MYSQL_HOST
        fromService:
          type: pserv
          name: mysqldb
          property: host
      - key: MYSQL_DATABASE
        value: films
      - key: MYSQL_USER
        value: produser
      - key: MYSQL_PASSWORD
        fromService:
          type: pserv
          name: mysqldb
          envVarKey: MYSQL_PASSWORD
      - key: MYSQL_ROOT_PASSWORD
        fromService:
          type: pserv
          name: mysqldb
          envVarKey: MYSQL_ROOT_PASSWORD

  # Frontend (Apache + HTML/JS)
  - type: web
    name: frontend-service
    runtime: docker
    repo: https://github.com/pabmarnav/Proyecto_Despliegue
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    rootScope: frontend
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend-service
          property: url
